### ISSUE TITLE
@ActionKey("gaomosi.ago") 映射路径 带dot .的 不能正常映射

### ISSUE THREAD

**Issue by jiftle** [jfinal/jfinal#102]
@ActionKey("gaomosi.ago")
映射路径 带dot .的 不能正常映射

**Comment by jfinal** [comment]
jfinal 示直接支持带 dot 的 url，所有带有 dot 的 url 将被视为静态资源请求。如果需要支持 .ago 这样的 url，可以用一下 Handler 做下转换，在 handler 中感知 xxx.ago 这样的 url，并将 xxx.ago 转成 xxx 即可。简单来说就是改变一下Handler.handel(...) 方法中的 String target 这个参数
