### ISSUE TITLE
Db.save(String tableName, Record record)  对象record新增属性之后必须remove

### ISSUE THREAD

**Issue by CrazyBeginner** [jfinal/jfinal#103]
Db.save(String tableName, Record record)  对象record新增属性之后必须remove掉，否则会报不存在该字段，可是有的时候随着业务的新增，对象record会新增一些与数据库不对应的属性，这个时候我又记不起来那些地方用了Db.save(String tableName, Record record) 了，能不能Db.save(String tableName, Record record)拼接sql字符串之前，与表的字段名称进行对比，自动去掉不存在的属性，避免因为不存在该字段而报告异常。

**Comment by jfinal** [comment]
Model 会自动处理字段是不是存在的问题，而 Db + Record 模式并没有用反射事先得到字段信息，不支持

建议使用 Model
