### ISSUE TITLE
jfinal 有完整的测试用例吗？

### ISSUE THREAD

**Issue by livem** [jfinal/jfinal#108]
我 fork 了一下 jfinal 的源码，里面不包括完整的测试用例、单元测试的。

可以增加进去？添加完新功能可以跑一遍测试保证代码质量。

个人提议。

**Comment by jfinal** [comment]
由于我自己的测试方式与常规方法完全不同，所以没有测试用例，有些人会误以为我没有把测试用例提交上来。我的测试方式是用单步调试，让程序走的路可以覆盖所有代码，并且动态调整变量值测试到一些测试用例难以达到的状态。 如果用测试用例去实现代码全覆盖测试，需要写很多很多的测试代码，并且随着项目自身的改变，还要去改测试代码，不仅无聊，而且工作量巨大

**Comment by livem** [comment]
也是，测试代码的维护，本身也是巨大的工作量

**Comment by jfinal** [comment]
传统测试用于业务项目是可以的，可以确保团队工作时的高质量，但对于 jfinal 这类极简的需要创造性的单人完成的框架来说就不适合了

**Comment by livem** [comment]
又学习到东西了，感谢作者

**Comment by livem** [comment]
或许对这类极简的框架的测试工作，也可以做创新

**Comment by RoonyLi** [comment]
我倒是觉得如果可以，最好还是有测试代码。虽然增加了工作量，但同时更能保证代码的可测试性。当然，我也很讨厌写测试。

**Comment by t3573393** [comment]
感觉有和jdt 集成的测试脚本放里面 也不错
