### ISSUE TITLE
运行main方法报错

### ISSUE THREAD

**Issue by jkgeekJack** [jfinal/jfinal#114]
```
public class Hello {
    public static void main(String[] args){
        JFinal.start("src/main/webapp", 8081, "/");
    }
}
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/jetty/server/Connector

**Comment by jfinal** [comment]
缺少 jetty 依赖而已，建议加入俱乐部，可以获取一个完整的最佳实践项目：http://jfinal.com/club
