### ISSUE TITLE
JFinal 3.0路由的问题

### ISSUE THREAD

**Issue by iamaprin** [jfinal/jfinal#115]
- 描述

定义两个路由
```java
@Override
public void configRoute(Routes me) {
    me.add(new ViewRoutes());
    me.add(new DataRoutes());
}
```

分别给两个路由设置baseViewPath：view和data
```java
import x.y.jfinal.web.controller.view.TestController;
public class ViewRoutes extends BaseRoutes {
    
    private static final String BASE_VIEW_PATH = "/view";
    
    @Override
    public void config() {
	setBaseViewPath(BASE_VIEW_PATH);
	add("/controllerKey",TestController.class);
    }
}
```
```java

import x.y.jfinal.web.controller.data.TestController;
public class DataRoutes extends BaseRoutes {

    private static final String BASE_VIEW_PATH = "/data";

    @Override
    public void config() {
	setBaseViewPath(BASE_VIEW_PATH);
	add("/controllerKey", TestController.class);
    }

}
```

但是这两个路由里面都定义了一个相同的controllerKey，会提示“controllerKey already exists”

- 疑问
`setBaseViewPath()`的描述是：Set base view path for controller in this routes，
所以判断controllerkey重复时，是不是应该加上此路由的baseViewPath？  
在JFinal初始化actionMapping时，是有调用`getFinalViewPath()`方法添加key的。

**Comment by iamaprin** [comment]
詹大，关于这个问题，请给我些指导。

**Comment by jfinal** [comment]
不是这么来理解的。 baseViewPath 指在调用 Controller.render(String view) 这个方法时，如果 view 这个变量不以 "/" 打头，那么将会用上 baseViewPath + viewPath + view 作为最终的 view 值，这个规则在本质上与 controllerKey 没有关系，controllerKey 保表达在 url 之中， 而 baseViewPath、viewPath、view 这三者都是表达在 render(...) 时的模板文件之中

**Comment by iamaprin** [comment]
这就意味着，我想定义/view/controllerKey和/data/controllerKey时，只能写全路径。有没有其他的方法，可以区分，而不用每个controllerKey都得写全。

**Comment by jfinal** [comment]
controllerKey 目前只支持写全路径，一个 controllerKey 唯一对应一个 Controller
