### ISSUE TITLE
dao.paginate  函数使用别名排序的时候抛异常

### ISSUE THREAD

**Issue by panjunjie** [jfinal/jfinal#117]
MySQL 数据库，使用分页函数 paginate ，其中排序为别名，抛异常，比如以下 SQL 语句：
select id,name,a,b,(a+b) as c from user order by c desc 
使用了 分页函数 dao.paginate 执行，就会抛异常：com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'c' in 'order clause'

**Comment by jfinal** [comment]
在最外层再套一个 select * 即可，这样来： paginate(1, 10, "select *", "from (原来的整个 sql) as temp", ...)

**Comment by panjunjie** [comment]
按照你的说法，可以用了，谢谢！

**Comment by panjunjie** [comment]
不过这种写法，对于新手来说，写法上有点奇怪，能否在 JFinal 层做下改动，让它更符合常见 SQL 写法？

**Comment by jfinal** [comment]
只要 select 语句块后续的 sql 部分不使用 select 块中取的别名，就不需要这样处理，你碰到的情况比较特殊，jfinal 对于分页做过很多思考，所以目前让用户提供的仅是一个拆分成两部分的查询 sql，用户对于具体怎么分页不需要关心，当然，在未来出现更好的方案时随时会改进，欢迎提建议
