### ISSUE TITLE
WEB-INF目录下新增jetty-web.xml文件，启动报错

### ISSUE THREAD

**Issue by wu-peng** [jfinal/jfinal#126]
WEB-INF目录下新增jetty-web.xml文件，内容如下
<?xml version="1.0"?>  
  <!DOCTYPE Configure PUBLIC "-//Mort Bay Consulting//DTD Configure//EN"  
  "http://jetty.mortbay.org/configure.dtd">
<Configure id="WebAppContext" class="org.eclipse.jetty.webapp.WebAppContext">
	<Set name="maxFormContentSize" type="int">1000000</Set>
</Configure>  

启动报错信息：
Object of class 'org.eclipse.jetty.webapp.WebAppContext' is not of type 'org.eclipse.jetty.webapp.WebAppContext'. Object Class and type Class are from different loaders.

**Comment by wangx1ng** [comment]
作者您好，请问是否有精力逐渐对 jfinal 的文档进行一些国际化的工作呢？

**Comment by jfinal** [comment]
@wangx1ng 国际化做过一些工作，看这里： https://github.com/jfinal/jfinal-manual

**Comment by jfinal** [comment]
@wu-peng 还没这么玩过，如果启不来，可以试试用 jetty 自带的启动方式，不要使用 JFinal.start(...)
