### ISSUE TITLE
注释有点怪怪的

### ISSUE THREAD

**Issue by Linuxea** [jfinal/jfinal#127]
core包下TypeConverter类 67行左右处的注释如下：
--------------------------------

// 经测试 JDBC 不会返回 java.util.Data 类型。java.sql.Date, java.sql.Time,java.sql.Timestamp 全部直接继承自 java.util.Data, 所以 getDate可以返回这三类数据

--------------------------------

应该是java.util.Date,还有后面的也是。

很抱歉我只能找出这样的非技术问题；）

**Comment by jfinal** [comment]
写注释可能一时手快，没写清楚。这里头有很多信息量没写进去：TypeConverter 对于 getModel 来说，是通过 JDBC 得到字段在 java 中的类型，而 JDBC 反射的测试结果并不会返回 java.util.Date 这个类型，只返回它的继承类

**Comment by Linuxea** [comment]
感谢詹老师的回信，我会再继续研究一下jfinal的源码和思维的。
不过我目前有一个问题，在拦截器方面我看到源码和jfinal介绍，好像是启动的时候初始化所有的controller,service的拦截器，通过判断有没有Before注解，有的话存储起来，可是有的问题我想不明白，也找不到具有说服力的代码片断。
第一：注解是在什么时候起作用的呢？
第二：注解是怎么起作用的？
据本人推测应该是每个controller执行Init方法时，

可是我还是找不出思路。

这个问题能否帮我解决一下？非常感谢詹总百忙之中抽空读到此。

致以对仍然处于一线开发者的您最真诚的敬意。

非常感谢。



linuxea@foxmail.com
 
发件人： James Zhan
发送时间： 2017-05-26 12:15
收件人： jfinal/jfinal
抄送： Linuxea; Author
主题： Re: [jfinal/jfinal] 注释有点怪怪的 (#127)
写注释可能一时手快，没写清楚。这里头有很多信息量没写进去：TypeConverter 对于 getModel 来说，是通过 JDBC 得到字段在 java 中的类型，而 JDBC 反射的测试结果并不会返回 java.util.Date 这个类型，只返回它的继承类

**Comment by jfinal** [comment]
controller 层之下的所有拦截器是在 jfinal 启动时一次性加载并缓存的，所以速度会非常之快，可以看一下 ActionMapping 与 InterceptorManager 这个类中的相关代码

由于 controller 层有一个 Routes 配置，所以可以实现 jfinal 启动时一次性加载并缓存。 而 service 层用户使用 enhance 的地方 jfinal 不方便去得到，所以 service 拦截器是在运行时加载并尽可能缓存，这部分代码在 aop 目录下的 Callback 中

具体是怎么起作用的，在合适的地方设置断点，通过单步调试即可知道

此外，有问题可以去 jfinal 社区发起：http://jfinal.com/feedback，github 我并不常用，所以这里不再回复这类问题
