### ISSUE TITLE
建议新增一些缓存操作方法

### ISSUE THREAD

**Issue by lyh061619** [jfinal/jfinal#131]
如：
1、新增findById的缓存查询方法。
2、清理缓存方法如：removeCache(String cacheName, Object cacheKey);
3、清理所有缓存方法： removeAllCache();

**Comment by jfinal** [comment]
很久以前就想加这个方法，但方法名不太好取名，例如 findByIdByCache、findByIdWithCache 这些都不合适，如果你有很好的名字，可以提给我

**Comment by lyh061610** [comment]
看这两个是否合适：
findByIdToCache
findById2Cache

**Comment by lyh061610** [comment]
看这两个是否合适：
findByIdToCache
findById2Cache

**Comment by jfinal** [comment]
这两个还不是行，主要是与原有方法不成系列，例如，原有方法有： findByCache   paginateByCache

**Comment by chenglongzjg** [comment]
findByIdFromCache ?

**Comment by lyh061610** [comment]
那就直接findByIdByCache算了。
