### ISSUE TITLE
在configRoute根据系统模块划分路由后获取不到Routes里的路由绑定参数

### ISSUE THREAD

**Issue by lyh061610** [jfinal/jfinal#132]
public class MyConfig extends JFinalConfig {
private Routes route;

@Override
public void configRoute(Routes me) {
me.add(new AdminRoutes()); //管理后台路由
me.add(new AgentRoutes());//代理商路由
me.add(new FrontRoutes());//前台会员路由
me.add(new ApiRoutes());//接口服务路由
this.route = me;
}
}
后routesList、routeItemList 的size值为0的，也就是这样传me后拿不路由映射值。

**Comment by jfinal** [comment]
单步调试跟踪一下，里面的代码并不多，相信能很快找到解决办法

**Comment by lyh061610** [comment]
确实不好说，调试进去是有值的，但传出来的就同有，如果不分块的话是能拿到。
