### ISSUE TITLE
jsonkit里无法生成 int的array的json，但是String的array可以。

### ISSUE THREAD

**Issue by aqnaruto** [jfinal/jfinal#134]
![image](https://user-images.githubusercontent.com/9067159/28491812-e0c9664a-6f29-11e7-9354-0462b4694b97.png)
波总您看这个stringarray是正常的。
但是intarray就没有值了
![image](https://user-images.githubusercontent.com/9067159/28491824-14e0cedc-6f2a-11e7-83f3-59aa1166baf0.png)

**Comment by pfjia** [comment]
@aqnaruto 


使用jfinal 3.4测试,没有出现你说的情况

``` java
    public static void main(String[] args) {
        int[] ints={1,2,5};
        Map<String,Object> map=new HashMap<>();
        Map<String,Object> innerMap=new HashMap<>();
        innerMap.put("title","ss");
        
        map.put("mapobj",innerMap);
        map.put("intArray",ints);
        map.put("intvalue",10086);
        System.out.println(JsonKit.toJson(map));
    }
```
结果如下:
`{"mapobj":{"title":"ss"},"intvalue":10086,"intArray":[1,2,5]}`

**Comment by jfinal** [comment]
2016 年发布的版本已经支持了这个功能，建议升级一下 jfinal
