### ISSUE TITLE
Db、DbPro、DbKit 三个类的功能类似的吗？

### ISSUE THREAD

**Issue by livem** [jfinal/jfinal#136]
就类名字来看，有点分不清这三个类分别是什么功能的，都是 数据库操作的工具类么？

Db. Powerful database query and update tool box.
DbPro. Professional database query and update tool.

可以看到 Db 都封装了 DbPro 里面的对应方法的。

Db 和 DbPro 区别在于什么地方呢？使用场景不同？求教求教，谢谢。

**Comment by jfinal** [comment]
Db 中的所有功能都是转调的 DbPro， Db 相当于一个静态工具类，是为了提升用户体验

DbKit 是辅助类，用户一般用不到，这里头有一些工具方法，例如：
DbKit.getConfig().getDataSource().getConnection();
