### ISSUE TITLE
欢迎提供skywalking APM插件

### ISSUE THREAD

**Issue by wu-sheng** [jfinal/jfinal#137]
skywalking APM之前一直在GitHub上发展，作为国内目前评星最高的自动探针Java Server APM项目，也是CNCF基金会下的OpenTracing支持列表中的分布式追踪项目。最近我们也加入了GVP，并谋求和国内的RPC、MVC框架的合作。

项目地址：https://github.com/wu-sheng/sky-walking

在上周，我们刚刚完成和[Nutz](https://github.com/nutzam/nutz) @nutzam 团队的高效合作，Thanks to @wendal。Nutz项目组完成了相关插件的提供，允许所有Nutz框架下的程序，都会被skywalking APM监控到，而开发者不需要修改任何的代码，也需要对Nutz的版本提出任何要求。

skywalking APM 团队，希望在国内的Java生态中，继续加强合作，所以真诚的希望，jfinal团队也能向skywalking团队提供针对jfinal MVC或生态下与远程、异步相关的插件。

希望得到项目组的回复。谢谢

skywalking PMC成员，@wu-sheng

**Comment by wu-sheng** [comment]
这是即将发布的下个版本的支持列表：https://github.com/wu-sheng/sky-walking/wiki/3.2.1-supported-list 
我们在争取让这个列表更丰富 ：）

**Comment by jfinal** [comment]
谢谢支持

**Comment by jfinal** [comment]
jfinal 社区的事情太多了，没有时间顾及很多事情
