### ISSUE TITLE
API changes report for JFinal

### ISSUE THREAD

**Issue by lvc** [jfinal/jfinal#139]
Hi,

I'd like to share report on API changes and backward compatibility for the JFinal library: https://abi-laboratory.pro/java/tracker/timeline/jfinal/

BC — binary compatibility
SC — source compatibility

The report is generated by the https://github.com/lvc/japi-tracker tool for jars at http://central.maven.org/maven2/com/jfinal/jfinal/. The tool checks for API changes according to the article https://wiki.eclipse.org/Evolving_Java-based_APIs_2.

Hope it will be helpful for users and maintainers of the library.

Thank you.

![jfinal-2](https://user-images.githubusercontent.com/1517837/32143139-15a28124-bcb6-11e7-8ce6-068c86717515.png)

![jfinal-1](https://user-images.githubusercontent.com/1517837/32143140-15c0998e-bcb6-11e7-98d3-fce1f60ca803.png)

**Comment by CrazyBeginner** [comment]
thank you for your share
