### ISSUE TITLE
特别想问一下jfnal是基于filter的吗？是基于方法的还是类的？如果是基于方法的，那么controller为什么不是单例的？

### ISSUE THREAD

**Issue by liepeng328** [jfinal/jfinal#141]
特别想问一下jfnal是基于filter的吗？是基于方法的还是类的？如果是基于方法的，那么controller为什么不是单例的？

**Comment by Linuxea** [comment]
jfinal 是基于 Filter 的，可以看下 web.xml 里面的配置到 JfinalFilter 以及众多的 handler,为什么不设计成单列的，我最近也在思考这个，可能更多是一个设计理念上的差异与具体设计上的妥协。

**Comment by liepeng328** [comment]
作者回答我这个问题了http://www.oschina.net/question/197668_221395
