### ISSUE TITLE
Need assign a readable name while invoking Controller.renderFile

### ISSUE THREAD

**Issue by Esmool** [jfinal/jfinal#144]
As title described.

Some time the generated file is stored with an internal name easy to manipulate, but when sending it to the customers, they want to have a human readable name instead. Current way is rename it in the file system before sending, or copy with a new name. That's a little waste of the disk and time costing.

Indeed, there is a header named Content-Disposition of HTTP protocol, can handle this. But changing it as follows doesn't seem to work:

...
this.getResponse().addHeader('Content-Disposition', '....');
this.renderFile(...);
...

Not before the invoking of renderFile(), nor after.

So, I'm wondering if you could add a method renderFile(File, String), with the second parameter specifying the filename that will write right in the Content-Disposition header of the response, help customers get readable filenames to save in their disk.

**Comment by jfinal** [comment]
This feature has been added， thank you for your feedback
