### ISSUE TITLE
getModel存在的设计缺陷

### ISSUE THREAD

**Issue by ukhack** [jfinal/jfinal#145]
## 使用场景
利用getModel接收前台传参
## 使用问题
getModel时：对于前台传来的参数，如果存在model中没有的参数，就会报错
```
com.jfinal.plugin.activerecord.ActiveRecordException:The model attribute xxx is not exists.
```
## 期望解决方案
往往前台传参不可能完全和model里面的值一模一样，会多几个其他的参数，对于这些参数model可以丢弃或者用其他如内置map的方式接收，但是不应该直接报错中断处理。

**Comment by ukhack** [comment]
## 状态
已解决
## 解决方法
滚去看了源码，发现了getModel的几个重载发方法，打扰了。。

**Comment by RoonyLi** [comment]
用getBean试试。model是给数据库用的。

**Comment by jfinal** [comment]
加一个 true 参数可以的
