### ISSUE TITLE
com.jfinal.kit.PathKit.setWebRootPath(String webRootPath),参数webRootPath有可能是空

### ISSUE THREAD

**Issue by wen3062** [jfinal/jfinal#15]
public static void setWebRootPath(String webRootPath) {
		if (webRootPath.endsWith(File.separator))
			webRootPath = webRootPath.substring(0, webRootPath.length() - 1);
		PathKit.webRootPath = webRootPath;
	}
这里的webRootPath有可能是空，我在用百度的Bea时，系统发布时，这个方法报空指针异常，应该是百度做了限制，不让获取绝对路径。

同样，在获取的方法中：
public static String getWebRootPath() {
		if (webRootPath == null)
			webRootPath = detectWebRootPath();
		return webRootPath;
	}
，却做了判断，我觉得在设置时，应该也做下判断，如下：
public static void setWebRootPath(String webRootPath) {
                 if (webRootPath == null）return;
		if (webRootPath.endsWith(File.separator))
			webRootPath = webRootPath.substring(0, webRootPath.length() - 1);
		PathKit.webRootPath = webRootPath;
	}

**Comment by jfinal** [comment]
都过去三年了，不好意思哈，我没有看 github 的习惯，感谢反馈，现在的 jfinal 已经到了 2.2 版了，功能极大完善了，建议升级
