### ISSUE TITLE
硬编码问题

### ISSUE THREAD

**Issue by SGYQ** [jfinal/jfinal#150]
SQL一定要放在业务层中，不利于维护吧？

**Comment by pig4cloud** [comment]
3.0 后边支持抽到模板里面 和mybatis 的用法差不多

**Comment by qinyou** [comment]
放在 配置文件中就很方便维护？

> SQL一定要放在业务层中，不利于维护吧？

**Comment by jfinal** [comment]
sql 不必放在业务层中，jfinal 提供了比 mybatis 强大、简洁、方便得多的 sql 管理功能，这里是具体用法：https://jfinal.com/doc/5-13

学习成本极低，用户体验极好
