### ISSUE TITLE
v3.6的代码，什么时候开放出来看啊？！！

### ISSUE THREAD

**Issue by noear** [jfinal/jfinal#157]
我看代码注释里说，v3.6会取消 Enhancer 。。。源码什么时候开放出来啊？？？很想看一下，稳不稳定不要紧：）

**Comment by noear** [comment]
再说点个人看法。。。集成的东西还是多了些：）

在企业里用时，企业还需要整合自己的东西。。。所以干净点，方便集成：）

**Comment by jfinal** [comment]
jfinal 主要在 gitee.com 上维护，github 上可能会慢一点。所有源码都是完全开源的

jfinal 内置的功能几乎都是最常用的，虽然迭代超过 8 年时间，功能很全，但到目前 4.8 版本的体量才 732KB，一个 jar 包搞定 web 开发大部分事情
