### ISSUE TITLE
jfianl jetty 版本升级

### ISSUE THREAD

**Issue by Spring3Coke** [jfinal/jfinal#158]
你好。使用jfinal 2.0 版本构建的基础架构，然后因为需要升级jetty版本至9.4，所以重写了JettyServer 这个类。但是在Jetty容器启动时，报了警告：
com.jfinal.server.JettyServer scanned from multiple locations: jar:
file: .../WEB-INF/lib/jfinal-2.0.jar!/com/jfinal/server/JettyServer.class, 
file: ...webapp/WEB-INF/classes/com/jfinal/server/JettyServer.class
这里想请问下，怎样才能规避掉这个警告内容呢？谢谢

**Comment by yufeng217** [comment]
这个问题我帮不上什么忙。
不过，你为什么要升级 jetty 到 9.4 呢？或者为什么不升级到 jfinal 最新版本呢？
还是你升级过程中遇到什么障碍了？

**Comment by Spring3Coke** [comment]
嗯嗯。因为我需要用到jetty 的websocket，而jetty 9.3 有bug，所以需要进行升级

**Comment by jfinal** [comment]
早已升级到 jetty 9 ，由于 jfinal 处理反馈大多都在自己的社区，github 上处理不及时，抱歉
