### ISSUE TITLE
这里不应该关掉管道，在和Spring集成的时候，运行经常报连接已断开，就是因为你这里这句代码

### ISSUE THREAD

**Issue by asanghehe** [jfinal/jfinal#159]
https://github.com/jfinal/jfinal/blob/662b73c3a03daaea51f95fff324fd65d0386045e/src/main/java/com/jfinal/template/Template.java#L61

**Comment by asanghehe** [comment]
http连接管理不应该被模板模块操作，除了写入数据。

**Comment by jfinal** [comment]
这个在早先的版本中已经改进，谢谢你的反馈
