### ISSUE TITLE
Model的findById方法, 当findById(null)时, 走的是可变参数的方法, 此时会NPE

### ISSUE THREAD

**Issue by sundongmin** [jfinal/jfinal#160]
```java
public M findById(Object idValue) {
    return findByIdLoadColumns(new Object[]{idValue}, "*");
}
public M findById(Object... idValues) {
    return findByIdLoadColumns(idValues, "*");
}
```
这两个方法是Model里的, 当调用时传**null**, 即, **findById(null)**, 走的是可变参数的方法, 这样就会报NPE

https://stackoverflow.com/questions/54159770/when-passing-null-as-argument-to-overloaded-varargs-methodobject-o-and-non
这是为什么会调可变参数的方法的原因

**Comment by jfinal** [comment]
为了解决这个问题，以及类型转换问题，2019 年上半年的新版本就将 findById 支持多参数的改成了 "findByIds" ，注意是方法名添加了一个字符 's'
