### ISSUE TITLE
🎉自动化接口和文档APIJSON已提供JFinal版

### ISSUE THREAD

**Issue by TommyLemon** [jfinal/jfinal#161]
🎉自动化接口与文档 ORM 库 APIJSON 已提供 JFinal 版的 Demo，名为 [APIJSONFinal](https://github.com/TommyLemon/APIJSON/tree/master/APIJSON-Java-Server/APIJSONFinal)

🚀后端接口和文档自动化，前端(客户端) 定制返回JSON的数据和结构！
https://github.com/TommyLemon/APIJSON

**Comment by jfinal** [comment]
谢谢支持
