### ISSUE TITLE
There is a vulnerability which can bypass the isSafeFile() function in JFinal ,so that I can upload any kind of files effectively

### ISSUE THREAD

**Issue by GlassyAmadeus** [jfinal/jfinal#171]
In JFinal , the upload function getFile() handle uploading files in this way :
1、handle upload request and upload all of the files in request without any safety precautions.
2、then judge the upload files and delete the dangerous files by isSafeFile() function.

However,  if I can try to create a exception which happened after upload and before isSafeFile() function , the dangerous files will upload to the server successfully.

So, I make a request like this 
![image](https://user-images.githubusercontent.com/54050849/62919892-9b707400-bdd6-11e9-885c-b98d828ef1ab.png)

In my code , I just accept file param like **getFile("file","test")** ，However I send a request which have two params("file" and "batchId") , the code will upload jsp file to the server and stop running before isSafeFile() function, since the code will catch an exception "java.io.IOException: Content disposition corrupt: Content-Disposition: form-data: name="batchId"" .

![image](https://user-images.githubusercontent.com/54050849/62920117-56990d00-bdd7-11e9-83b0-4dca51becfef.png)

**Comment by jfinal** [comment]
This problem belongs to project cos, and it has been fixed:
[https://gitee.com/jfinal/cos/commit/5eb23d6e384abaad19faa7600d14c9a2f525946a](https://gitee.com/jfinal/cos/commit/5eb23d6e384abaad19faa7600d14c9a2f525946a)

[https://gitee.com/jfinal/cos/commit/8d26eec61f0d072a68bf7393cf3a8544a1112130](https://gitee.com/jfinal/cos/commit/8d26eec61f0d072a68bf7393cf3a8544a1112130)

Thanks for your feedback
