### ISSUE TITLE
提交一个上传漏洞

### ISSUE THREAD

**Issue by luoke90hou** [jfinal/jfinal#172]
![image](https://user-images.githubusercontent.com/54087891/62991906-104db780-be84-11e9-8d15-d8632122cd2b.png)

将batchid参数放最下面，然后去掉末行的boundary，可以绕过jsp黑名单。虽然提示失败，但实际上传成功了。
![image](https://user-images.githubusercontent.com/54087891/62992260-5ce5c280-be85-11e9-8caf-2e2b4db6a4ed.png)
原理大概是先上传再鉴定黑名单去删除文件，这样轮询参数的时候如果提供错误参数，就会报错，程序终止，就不会删除文件了。

**Comment by eceye** [comment]
这个应该是传到临时文件夹了吧

**Comment by luoke90hou** [comment]
> 这个应该是传到临时文件夹了吧

会上传到正常目录

**Comment by jfinal** [comment]
@luoke90hou  @eceye  这个是第三方上传组件 cos 的问题，已经更新了 cos 项目并上传到了 maven 中心库，具体改动见这里：
[https://gitee.com/jfinal/cos/commit/8d26eec61f0d072a68bf7393cf3a8544a1112130](https://gitee.com/jfinal/cos/commit/8d26eec61f0d072a68bf7393cf3a8544a1112130)

[https://gitee.com/jfinal/cos/commit/5eb23d6e384abaad19faa7600d14c9a2f525946a](https://gitee.com/jfinal/cos/commit/5eb23d6e384abaad19faa7600d14c9a2f525946a)
