### ISSUE TITLE
Enjoy 模板引擎 #date支持LocalDateTime吗

### ISSUE THREAD

**Issue by ojbk-666** [jfinal/jfinal#179]
Enjoy 模板引擎 支持LocalDateTime吗

**Comment by jfinal** [comment]
目前不支持， 但你可以很容易扩展一个，步骤如下：
1：复制一份 DateDirective 代码出来，添加支持 LocalDateTime 的功能，改类名为 MyDateDirective
2：移除系统原有的 #date 指令：engine.removeDirective("date");
3：添加自己扩展的 #date 指令：engine.addDirective("date", MyDateDirective.class, true);

后续版本考虑支持这个功能

**Comment by jfinal** [comment]
jfinal 4.9.02 新增了这个支持:
[https://gitee.com/jfinal/jfinal/blob/master/src/main/java/com/jfinal/template/ext/directive/DateDirective.java](https://gitee.com/jfinal/jfinal/blob/master/src/main/java/com/jfinal/template/ext/directive/DateDirective.java)

新版本代码会在推送 maven 之前提交到 github 上来，这次国庆长假会迭代一个新版本
