### ISSUE TITLE
Record.java java.util.Date getDate(String column) 做强制类型转换会报错

### ISSUE THREAD

**Issue by funnyrabbit87** [jfinal/jfinal#186]
使用JDK8  mysql 8.23 的jdbc ，对于数据库datetime字段，jdbc返回的值类型是java.time.LocalDateTime
ISO 8601格式 如2021-01-30T09:00:00
java.util.Date getDate(String column) 将值做强转会导致异常.

**Comment by jfinal** [comment]
Model、Record 的 getDate 已添加对于 LocalDateTime、LocalDate、LocalTime 的自动转换机制。

并且 Db、DbPro 已添加 queryLocalDateTime。

并且 DbTemplate 也已添加 queryLocalDateTime，请尽快使用，尽早反馈，以便发布新版本
