### ISSUE TITLE
关于Validator中添加对url中v1-v2参数的验证

### ISSUE THREAD

**Issue by richxnh** [jfinal/jfinal#19]
如下所示：

private void validateRequiredValue(String value, String errorKey, String errorMessage) {
	if (value == null || "".equals(value)) // 经测试,无输入时值为"",跳格键值为"\t",输入空格则为空格" "
		addError(errorKey, errorMessage);
}

protected void validateRequired(String field, String errorKey, String errorMessage) {
	validateRequiredValue(controller.getPara(field), errorKey, errorMessage);
}

protected void validateRequired(int index, String errorKey, String errorMessage) {
	validateRequiredValue(controller.getPara(index), errorKey, errorMessage);
}

**Comment by jfinal** [comment]
早几个版本前已添加此功能，感谢反馈
