### ISSUE TITLE
com.jfinal.core.Controller 能把_init_方法改为public么？

### ISSUE THREAD

**Issue by creky** [jfinal/jfinal#198]
如题，偷懒用的~~用于在初始化controller的时候设置一些固定的参数

**Comment by Creky** [comment]
`public class UniControllerFactory extends ControllerFactory {
    @Override
    public Controller getController(Class<? extends Controller> controllerClass) throws ReflectiveOperationException {
        var controller = super.getController(controllerClass);
        if(controller instanceof UniControllerInterface){
            ((UniControllerInterface)controller).init(controller.getRequest(),controller.getResponse());
        }
        return controller;
    }
}
`

已经解决

**Comment by Creky** [comment]
实际上此处是在 controller._init_(action, request, response, urlPara[0]); 执行之前，导致上述controller.getRequest(),controller.getResponse()均为null，所以上述操作是无效的，还是需要把controller._init_设置为public才好~~~

**Comment by jfinal** [comment]
这个方法一直是通过 CPI 开放出来的，用一下 CPI._init_(....)，类似的地方有很多，在各个模块下的 CPI.java 中
