### ISSUE TITLE
分布式验证码有文档吗

### ISSUE THREAD

**Issue by manyhelp** [jfinal/jfinal#199]
单机、集群，两种方式的验证码有文档吗？

**Comment by ysjsgzq** [comment]
自己写一个类，实现 ICaptchaCache  接口。 然后在 Config 类的configConstant 方法里面 me.setCaptchaCache(new 你自己写的类)

**Comment by manyhelp** [comment]
> 自己写一个类，实现 ICaptchaCache 接口。 然后在 Config 类的configConstant 方法里面 me.setCaptchaCache(new 你自己写的类)

还需要自己写个CaptchaRender 类吧，不然怎么生成验证码 put 到 ICaptchaCache

**Comment by ysjsgzq** [comment]
> > 自己写一个类，实现 ICaptchaCache 接口。 然后在 Config 类的configConstant 方法里面 me.setCaptchaCache(new 你自己写的类)
> 
> 还需要自己写个CaptchaRender 类吧，不然怎么生成验证码 put 到 ICaptchaCache

直接调用官方的验证码生成方法，官方会调用你的验证码保存和获取方法。不用自己写CaptchaRender

**Comment by manyhelp** [comment]
能麻烦贴一下例子吗
