### ISSUE TITLE
configPlugin 方法中Plugins 优化

### ISSUE THREAD

**Issue by 0x0001** [jfinal/jfinal#24]
目前Plugins 的 add方法只能接受一个IPlugin,如果有多个plugin的时候,使用方式i类似
`me.add(new Plugin1()).add(new Plugin2());`
如果使用变参,写法就可以这样
`me.add(new Plugin1(),new Plugin2());` 插件多的时候可以少写好多add啊,这样看起来也很清晰

**Comment by jfinal** [comment]
功能很早几个版本已实现，感谢反馈
