### ISSUE TITLE
建议将log4j更换为logback吧，更加灵活的log日志使用

### ISSUE THREAD

**Issue by gumutianqi** [jfinal/jfinal#29]

**Comment by livem** [comment]
我看到其他的项目里面，都用 `slf4j` 就好了，最终用户使用哪个 `log` 实现都没所谓。

**Comment by jfinal** [comment]
肯定会换的，还没顾上，目前最关键是 jfinal 2.3

**Comment by aqnaruto** [comment]
log4j2 比logback好，不需要换。

**Comment by jfinal** [comment]
@aqnaruto 已做备忘，感谢反馈

**Comment by aqnaruto** [comment]
谢谢波总回复，jfinal造福很多人，jfinal是我找到的是唯一能够在效率上和php pk的框架

**Comment by jfinal** [comment]
@aqnaruto  感谢你的支持，近期将发布 jfinal 3.2，有很多的打磨，针对大家的反馈做了必要的改进，平滑升级。时间关系，这次你的反馈只能待到 jfinal 3.3 去处理了

**Comment by lyh061610** [comment]
@aqnaruto @jfinal jfinal底层不是使用preparedStatement这个的嘛，天然就是支持防sql注入的呢，所以就什么sql注入的过以略过了，至于xss这类的话确实是要增强下的。

**Comment by jfinal** [comment]
谢谢你们的建议，jfinal 4.8 添加了对 slf4j 的支持，并添加了可变参数，而且添加了 trace 日志级别

使用 slf4j 的配置很方便：
me.setToSlf4jLogFactory();

建议升级到 4.8 ，功能添加得有点晚，抱歉
