### ISSUE TITLE
分页查询的潜在问题

### ISSUE THREAD

**Issue by joaboo** [jfinal/jfinal#34]
Model类中的paginate方法,不明白为什么要在参数中把整句的sql分成String select,String sqlExceptSelect两个参数..看了下源码,觉得作者应该是为了count total的便于拼接count sql..代码如下: 
List result = Db.query(conn, "select count(\*) " + DbKit.replaceFormatSqlOrderBy(sqlExceptSelect), paras);
这样简单粗暴的处理显然存在隐患..如果我的sql为"select distinct c from t",那这时count的sql就会拼接成"select count(\*) from t",显然是不对的...

个人觉得有必要简单的解析下sql,甚至必要时可以开放传入参数为String sql, String countsql的方法..

**Comment by jfinal** [comment]
可以通过将原有的 sql 外面套一层来解决，这样有和：paginate(1, 10, " select * ", from (原有sql) as temp", paras)
