### ISSUE TITLE
本地maven安装jfinal报如下错误

### ISSUE THREAD

**Issue by lucasyue** [jfinal/jfinal#35]
D:\git\jfinal\src\com\jfinal\plugin\activerecord\Db.java:[161,20] 无法确定 <T>T 的类型参数；对于上限为 T,java.lang.Object 的类型变量 T，不存在唯一最大实例
[ERROR] D:\git\jfinal\src\com\jfinal\core\ModelInjector.java:[36,15] 无法确定 <T>T 的类型参数；对于上限为 T,java.lang.Object 的类型变量 T，不存在唯一最大实例
[ERROR]

原因：没有强转为(T)，我本地jdk1.6，不知道版主是否存在该问题？

**Comment by peidachang** [comment]
jdk1.6.0_16版本会有这个问题，升级到jdk1.6.0_25版本以上即可
