### ISSUE TITLE
PathKit.getRootClassPath()空指针问题

### ISSUE THREAD

**Issue by chenleijava** [jfinal/jfinal#46]
使用jetty作为容器，打包jar运行，发现PathKit.getRootClassPath()在jar中使用会抛出空指针异常，根本无法获取到path，修改测试如下：
private static final String rootClassPath="/";
	public static String getRootClassPath() {
		return rootClassPath;
	}
运行ok。

**Comment by jfinal** [comment]
单独将web项目打成jar来运行，很少有成功的，希望你能分享出来是怎么做的
