### ISSUE TITLE
logger debug方法在jdklogger实现下无效

### ISSUE THREAD

**Issue by b1412** [jfinal/jfinal#5]
debug无法打出日志。
另外建议jfianl logger 支持 logger.debug(String template,Object ...args);这样的方法。
因为在很多日志系统里面已经有可变参数打日志了。
比如logback支持这样的日志logger.debug(" a is {},b is {}, c is{}",a,b,c);

我先试着实现一下，然后你看看代码

**Comment by jfinal** [comment]
谢谢你们的建议，jfinal 4.8 添加了对 slf4j 的支持，并添加了可变参数，而且添加了 trace 日志级别

使用 slf4j 的配置很方便：
me.setToSlf4jLogFactory();

建议升级到 4.8
