### ISSUE TITLE
JdkLogger打印日志时候方法名不是调用类中的方法名

### ISSUE THREAD

**Issue by ghost** [jfinal/jfinal#54]
Logger logger = Logger.getLogger("");
 logger.info("123");

结果打印出
一月 19, 2015 5:56:58 下午  info
信息: 123

在JdkLogger中用
log.logp(Level.INFO, clazzName, Thread.currentThread().getStackTrace()[2].getMethodName(), message);可以正确获取方法名。

**Comment by jfinal** [comment]
目前的代码是：log.logp(Level.INFO, clazzName, Thread.currentThread().getStackTrace()[1].getMethodName(), message);，应该是可以输出 methodName的，可能是配置问题。另外建议使用Log4jLog
