### ISSUE TITLE
需要一个JsonPRender 

### ISSUE THREAD

**Issue by xurenlu** [jfinal/jfinal#59]
如题,建议增加一个jsonPrender:
class SomeController extends Controller {
public void test(){
Object someObject =new Object();
callback=getPara("callback");
  renderJsonP(someObject,callback);
}
}

输出:
callback({});

**Comment by jfinal** [comment]
renderText(String, ContentType) 这个方法能满足需要不？

**Comment by xurenlu** [comment]
@jfinal 可以实现,稍微多写几行代码.但是从框架的角度来说,还是提供renderJsonP 方便一些.我自己用的时候 ,是直接修改了jfinal的源码,从JsonRender继承了一个.
如果不提供的话,对于大量使用jsonp做输出的时候 ,每次输出都要调 json encode的过程,代码有大量重复.

**Comment by aqnaruto** [comment]
波总没必要听他的，这种东西完全没必要，jsonp已经淘汰了 现在都用fetch
