### ISSUE TITLE
如何对Model进行单元测试?

### ISSUE THREAD

**Issue by xurenlu** [jfinal/jfinal#60]
如题,写了这么一段单测代码,但是无法跑起来,
@Test
    public void testUser(){
        User u = new User();
        u.set("username","renlu");
        u.set("password","842519");
        u.set("email","xurenlu@gmail.com");
        long t = (new Date()).getTime()/1000;
        u.set("created_at",t);
        u.set("updated_at",t);
        u.save();
    }

如果需要跑这么一段代码,需要运行一个web server实例...
能不能提供一个简单点的能运行单测的case?

**Comment by jfinal** [comment]
在初始化方法中创建 ActiveRecordPlugin 对象，并且 arp.start() 启动它即可开始使用 ActiveRecordPlugin，具体方法可看这里：http://www.oschina.net/question/173052_59956。另外，jfinal 单元测的一些支持可以看下这里：http://git.oschina.net/zhouleib1412/jfinal-ext/tree/master/src/main/java/com/jfinal/ext/test，这里面有辅助单元测试使用的 Mock 类
