### ISSUE TITLE
jfinal 1.9 store java.util.Date into Postgresql error

### ISSUE THREAD

**Issue by rcn-neo-yang** [jfinal/jfinal#63]
error : Caused by: org.postgresql.util.PSQLException: Can't infer the SQL type to use for an instance of java.util.Date. Use setObject() with an explicit Types value to specify the type to use.

Java version : 8
开发工具：eclipse Luna Service Release 1 (4.4.1)
DB：postgresql
场景：修改blog demo，input type="date" in "_form.html"

源代码
class: com.jfinal.core.Controller 
     method: private Date toDate(String value, Date defaultValue) {
          code: return new java.text.SimpleDateFormat("yyyy-MM-dd").parse(value);
     import java.util.Date;

更新为 
class: com.jfinal.core.Controller 
     method: private Date toDate(String value, Date defaultValue) {
          code: return new java.sql.Date(new java.text.SimpleDateFormat("yyyy-MM-dd").parse(value).getTime());
     import java.sql.Date;

解决！

参考：google error 搜索出来的部分解决办法 ：）

**Comment by jfinal** [comment]
做这个选择需要再考虑，你的代码相当于将 java.util.Date 转成了 java.sql.Date，但前一个 Date 更通用，通常数据库都对前面的Date支持很好。 希望你能测试一下 postgresql的date字段这样： model.set(xxx, new java.util.Date()).save(); 看能否直接支持 java.util.Date

**Comment by rcn-neo-yang** [comment]
谢谢回复，经测试postgresql确实不支持java.util.Date。
