### ISSUE TITLE
2.0版本发布了，maven中央仓库没有同步提交？

### ISSUE THREAD

**Issue by tcwdsg** [jfinal/jfinal#66]
如题

**Comment by jfinal** [comment]
maven 中央库最近总超时，天朝的网络你懂的，maven 用户可以先下载jar 包，然后这样用起来：mvn install:install-file -DgroupId=com.jfinal -DartifactId=jfinal -Dversion=2.0 -Dpackaging=jar -Dfile=jfinal-2.0-bin.jar

**Comment by tcwdsg** [comment]
收到，谢谢

**Comment by jfinal** [comment]
上周已发布成功 maven，可以用了
