### ISSUE TITLE
关于jfinal的路由的通配符的支持？

### ISSUE THREAD

**Issue by yuanwhy** [jfinal/jfinal#67]
jfinal不能通过设置一个通用的路由吗？比如像这样  
   
     me.add("/{ControllerName}/{ActionName}", "{ControllerName}Controller.class", "ActionName");
 
这样就不用每个控制器都要写一个路由了

**Comment by jfinal** [comment]
基于现在的 jfinal 路由，写一个 class AutoRutes extends Routes 即可，已经很多项目在这么做了，具体可以去搜索一下 oschina.net 中的 jfinal extensions 项目

**Comment by henrywhy** [comment]
试了一下ext的自动路由的功能，确实满足了功能需求，很nice. 不知道作者用过asp.net mvc没有，微软对于mvc框架的处理，凭良心讲，真的是非常方便易用，比如url路由这块做的就很直观而简单，反观struts2，恶心至极；可以学习一下微软的一些优秀做法，如果有可能，希望jfinal能超越struts2

**Comment by jfinal** [comment]
微软的 mvc 没有用过，它的url路由具体怎么用的呢？ 还请在此给个例子，我看能不能吸收一下他的长处

**Comment by henrywhy** [comment]
public class RouteConfig
    {
        public static void RegisterRoutes(RouteCollection routes)
        {
            routes.IgnoreRoute("{resource}.axd/{*pathInfo}");

            routes.MapRoute(
                name: "Default",
                url: "{controller}/{action}/{id}",
                defaults: new { controller = "Home", action = "Index", id = UrlParameter.Optional }
            );
        }
    }

上面这个是asp.net mvc 框架新建项目之后默认生成的路由配置，实现的效果和jfinal+ext的效果是一样的，不过这个路由配置的可读性非常强，模式匹配的方式直观地表明url中哪个是控制器名、哪个是方法名，大部分情况下默认路由就能满足需求；对路由重写也是很方便的，比如blog文章出于seo的需要必须重写一条路由，直接在默认路由前面再加一条 
         routes.MapRoute(
                name: "Blog",
                url: "blog/{seo-name}",
                defaults: new { controller = "Blog", action = "List", seo-name="hello-world" }
           );

总结：借鉴计算机网路中路由器的配置原理，url路由有一个路由表，路由表由若干条路由组成，优先级由注册顺序决定，一条路由有路由名、url格式(可通配)、默认值等属性。

jfinal现在的路由是这种机制的
             me.add("/hello", HelloController.class);
虽然加上了ext，但是ext在重写路由的时候需要注解的方式，不是很方便。而造成现在路由配置种种不便的原因，我觉得主要基于两点：
     1、对路由的抽象程度不够，最好一条路由应该是一条记录，具有通配的能力，与具体的控制器类无关
      2、路由配置分散，最好所有路由由路由表统一管理，优先级由顺序来定，这样能在路由表中能一眼分析出某条url会访问哪个方法，而不需要再翻到某个类里面去看它的注解而去判断优先级

**Comment by gefangshuai** [comment]
个人感觉通过注解的方式更直观而且省时省力

**Comment by jfinal** [comment]
已备忘，感谢反馈，下一版本考虑添加这个支持
