### ISSUE TITLE
注解加载问题

### ISSUE THREAD

**Issue by liboyue23** [jfinal/jfinal#71]
我看了jfinal的AOP，用的@before注解，按道理说应该是在服务启动的时候，读取扫描指定包下面类或者方法上面的注解，反射实例化执行代码，然而我在InterceptorBuilder找到了类似加载before注解的代码，但是在服务启动的时候debug不执行这块，那么请问，注解那块到底在哪实现反射的？

**Comment by jfinal** [comment]
看一下 jfinal 2.0 手册第 4.5 章节，里面讲述了 Interceptor 的触发方式。对于控制层的拦截器是自动触发的，对于控制层以外的地方，需要 Duang.duang(target) 对目标进行一下增强

**Comment by jfinal** [comment]
对于控制层拦截来说，Interceptor 的创建与初始化是在系统启动时一次搞完成的，而且对拦截器栈都是缓存起来的，所以后续不会再有加载，也不会再有反射操作，性能达到极致。对于业务层来说，拦截器是在调用时动态加载的
