### ISSUE TITLE
文件上传能否将自动重命名集成到框架里？

### ISSUE THREAD

**Issue by gefangshuai** [jfinal/jfinal#72]
每次都要自己封装一个工具方法来获取`UploadFile`，然后自己实现重命名的功能，`jfinal`框架里能否将重命名的功能集成到框架中，让开发者有可选择的余地，个人感觉这样做不会加重框架吧？

毕竟大多数情况是需要将用户上传的文件重命名到存储服务器进行存储。还望权衡一下！

**Comment by jfinal** [comment]
已做备忘，下一版本考虑支持，感谢反馈
