### ISSUE TITLE
oss-parent已经DEPRECATION WARNING了，还继续用吗？

### ISSUE THREAD

**Issue by kingzone** [jfinal/jfinal#75]
今天看到https://github.com/sonatype/oss-parents 主页里oss-parent已经DEPRECATION WARNING了，还继续用吗？jfinal里用了oss-parent的哪些东西呢？

**Comment by jfinal** [comment]
这个 oss-parent 是传用于将项目发布到 maven 中心库的，对开发没有任何影响，不知道你有何建议，一直没有时间研究这个 oss 的东东，目前发布到 maven 中心库是正常的

**Comment by jfinal** [comment]
后续的 jfinal 已经修改了 pom.xml，新的 oss 配置不会出现提示
