### ISSUE TITLE
java.sql.SQLException: Operation not allowed after ResultSet closed

### ISSUE THREAD

**Issue by orjuly** [jfinal/jfinal#76]
java.sql.SQLException: Operation not allowed after ResultSet closed
    com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1078)
    com.mysql.jdbc.SQLError.createSQLException(SQLError.java:989)
    com.mysql.jdbc.SQLError.createSQLException(SQLError.java:975)
    com.mysql.jdbc.SQLError.createSQLException(SQLError.java:920)
    com.mysql.jdbc.ResultSetImpl.checkClosed(ResultSetImpl.java:804)
    com.mysql.jdbc.ResultSetImpl.realClose(ResultSetImpl.java:7331)
    com.mysql.jdbc.ResultSetImpl.close(ResultSetImpl.java:923)
    com.mysql.jdbc.StatementImpl.realClose(StatementImpl.java:2585)
    com.mysql.jdbc.PreparedStatement.realClose(PreparedStatement.java:3158)
    com.mysql.jdbc.StatementImpl.close(StatementImpl.java:577)
    com.alibaba.druid.filter.FilterChainImpl.statement_close(FilterChainImpl.java:2386)
    com.alibaba.druid.filter.FilterAdapter.statement_close(FilterAdapter.java:2446)
    com.alibaba.druid.filter.FilterChainImpl.statement_close(FilterChainImpl.java:2383)
    com.alibaba.druid.filter.stat.StatFilter.statement_close(StatFilter.java:311)
    com.alibaba.druid.filter.FilterChainImpl.statement_close(FilterChainImpl.java:2383)
    com.alibaba.druid.proxy.jdbc.StatementProxyImpl.close(StatementProxyImpl.java:124)
    com.alibaba.druid.pool.DruidPooledStatement.close(DruidPooledStatement.java:294)
    com.alibaba.druid.pool.DruidPooledPreparedStatement.closeInternal(DruidPooledPreparedStatement.java:209)
    com.alibaba.druid.pool.DruidPooledConnection.closePoolableStatement(DruidPooledConnection.java:172)
    com.alibaba.druid.pool.DruidPooledPreparedStatement.close(DruidPooledPreparedStatement.java:201)
    com.jfinal.plugin.activerecord.DbKit.closeQuietly(DbKit.java:94)
    com.jfinal.plugin.activerecord.Model.find(Model.java:510)
    com.jfinal.plugin.activerecord.Model.find(Model.java:525)

该异常是通过 ./bin/btrace java进程id ./samples/OnThrow.java 看到的,并且该异常已经验证影响线上的性能
说明：代码中没有手动显示关闭ResultSet 和Statement，所有的dao都是集成jfinal的Model类

**Comment by jfinal** [comment]
这个问题很奇怪，异常信息表明由于ResultSet在被关闭的情况下，有对它继续再使用的迹象，比较怀疑是jdbc驱动的bug，建议升级一下 jdbc驱动，以及 druid 版本。 jfinal 2.2 版本针对这个问题，改进了一下 result set 的关闭操作，对关闭操作的异常做了日志，以后就再也不必使用 btrace java 进程id的方式知道这个异常了。非常希望你能后续给予反馈，该问题这是第一次碰到，所以你的反馈极端重要，谢谢
