### ISSUE TITLE
请问怎么在控制台显示错误日志啊?

### ISSUE THREAD

**Issue by oldfeel** [jfinal/jfinal#77]
````
		AnswerItem answerItem = new AnswerItem().set("user_id", user_id).set("question_id", question_id)
				.set("content", content).set("create_time", create_time).set("addr", addr).set("lat", lat)
				.set("lon", lon).set("images", images).set("addr_info", addr_info);
		answerItem.save();
````
打断点发现在 answerItem.save(); 时出现异常,返回 500.但是控制台没有显示异常信息.请问怎么配置才会显示异常信息?

**Comment by giscafer** [comment]
错误信息肯定会输出的呀。configConstant里的me.setDevMode(true);也只是一些开发模式设置的信息的输出

**Comment by oldfeel** [comment]
@giscafer 我在配置信息里有设置 me.setDevMode(true); 最后排查发现是 content 里的包含 emoji 字符串,而使用的 mysql-connectionrt-java 版本太低,导致插入失败,但是控制台确实没有显示错误信息.

**Comment by jfinal** [comment]
@oldfeel  控制台要输出异常信息，日志配置文件需要弄好，在官网下载 demo，参考一下里面的 log4j.properties 文件，在此下载: http://www.jfinal.com
