### ISSUE TITLE
1.8升级到2.0后,拦截器清除@Clear不起作用了

### ISSUE THREAD

**Issue by priest1234** [jfinal/jfinal#78]
//1.8版 
       //@ClearInterceptor(ClearLayer.ALL)
	@Clear
	@Override	
	public void index() {
		System.out.println("测试");
	}

**Comment by jfinal** [comment]
jfinal 2.0 的 Clear 用法稍有变化，支持清除指定的拦截器了，详见 jfinal 手册

**Comment by priest1234** [comment]
ok,已经解决，谢谢
