### ISSUE TITLE
jfinal2.1版本中，Db.paginate组装sql语句问题

### ISSUE THREAD

**Issue by ewill** [jfinal/jfinal#80]
这个版本的Db.paginate把sql语句都合并成了一个参数进行传递，觉得非常好，但是当我的select语句中带有子查询的时候，select count(*)的组装就错乱了，导致数据库执行的时候报错。
举个栗子：

select a.xx, a.yy (select some from xxx_table where xxx = xxx) as t
from yyy_table
where ....
类似这样的格式

然后select count(*)的组装就错乱了。
在以前的版本，我一直这样写，是没有问题的，新版本就有问题了
jfinal2.1之前的版本没有这个问题

**Comment by jfinal** [comment]
@ewill 这个问题会在最近几天改进，maven中央库之所以还没有发布，就是为了这几的考验期，这样才完美，感谢反馈

**Comment by jfinal** [comment]
@ewill 这个问题会在最近几天改进，maven中央库之所以还没有发布，就是为了这几的考验期，这样才完美。元月 4 号的时候记得来群里找群主要内部体验版，感谢反馈

**Comment by ewill** [comment]
@jfinal 我想问问jfinal的群现在哪个能进去的？我在jfinal官方网上的群号说不存在。

**Comment by jfinal** [comment]
@ewill 322076903  432462639
