### ISSUE TITLE
getModel和el表达式填充表单的时候model属性同时存在下划线和驼峰式，看起来好奇怪

### ISSUE THREAD

**Issue by YuanKJ-** [jfinal/jfinal#82]
<  . input class="easyui-textbox m_textbox" type="text" id="idCard" name="user.id_card" value="${user.idCard}" data-options="required:true,validType:'length[15,18]'"  />

为了使用getModel方法，input标签的name属性要配合model命名，在model的get方法中是驼峰式命名，但是因为数据库中该字段是下划线式命名，所以要使用user.id_card这种命名方式，然而，填充的时候el表达式要使用user.idCard这种驼峰式命名，看起来很不一致很奇怪.

这不是一个很严重的bug，但是强迫症就是想来提个issue，作者可以忽略掉。。

**Comment by jfinal** [comment]
@YuanKJ 如果是使用mysql数据库，可以将数据表字段直接使用驼峰命名形式，最快地就解决了问题。如果不这样解决，但是使用了 jfinal 2.1 的 Generator为Model生成了getter 和setter的话，直接用 getBean(...) 代替 getModel(...)，就可以解决，试用后再回来反馈一下哈

**Comment by YuanKJ-** [comment]
卧槽，66666，问题解决，谢谢

**Comment by jfinal** [comment]
@YuanKJ- jfinal 2.1 用着感觉如何？

**Comment by YuanKJ-** [comment]
非常好，model自动生成真是节省了我太多功夫了，我们三个同事都在用2.1了，赞一个

**Comment by jfinal** [comment]
@YuanKJ- 用上生成器，建议 json这块切到jackson或 fastjson上去，JsonManager.setDefualtJsonFactory(JacksonFacotry.me());

**Comment by YuanKJ-** [comment]
用默认的JFinalJsonFactory跟切到fastjson这些有什么区别吗？我现在是用默认的没有更改

**Comment by jfinal** [comment]
@YuanKJ- JFinalJson 转换 model 时，会保持着字段名的下划线命名，例如： {"user_name": "james"}，因为它是依赖于 Model.attrs 这个map来转换的，而 jackson 是依赖于 getter 方法名来转的。jfinal 会在下一个版本中改进一下，将 JFinalJson 提供一个参数供选择，使用 JFinalJson 也可以做个驼峰命名的转换，当前 jfinal 2.1 还没这个功能

**Comment by YuanKJ-** [comment]
好的了解

**Comment by jfinal** [comment]
建议升级到 jfinal 2.2 版本，这是一个 bug修改版，修复了两个bug，升级也是分分钟的事
