### ISSUE TITLE
FileRender 能否增加一个设置文件名的方法

### ISSUE THREAD

**Issue by shuaqiu** [jfinal/jfinal#86]
如题, 项目中保存的资源的文件名是生成的UUID 来的, 如果直接使用这个文件名, 则下载弹出的文件名完全看不出是什么了, 能否提供一个设置下载文件名的方法, 用于设置`Content-disposition` 里面显示的文件名.

**Comment by jfinal** [comment]
@shuaqiu 这个功能已经添加上了，jfinal 2.3 会发布出来，目前建议你自建一个 MyFileRender extends FileRender 来实现，这样用 render(new MyFileRender(file,  fileName));

**Comment by shuaqiu** [comment]
什么时候会发布哦? 如果快的话, 我看是不是直接升级版本了.

**Comment by RoonyLi** [comment]
我pull 了一个版本，@jfinal  @shuaqiu 可以看下。
