### ISSUE TITLE
ActiveRecord 连接未关闭bug

### ISSUE THREAD

**Issue by 0x0001** [jfinal/jfinal#87]
当在一个线程中使用Model中的方法进行了数据库操作 (`findFirst` 等), 退出这个方法时,连接并未释放,放在threadlocal缓存,但是线程可能是临时的(非线程池,或者线程池因为负载问题自动降低容量时)连接泄露

暂时解决办法是, 在线程中访问数据库都用`Db.tx(IAtom)` 来进行包裹

**Comment by pfjia** [comment]
@0x0001 我看了jfinal 3.4的源码
1.使用Model.findFirst()等方法时会调用Model.find()
``` java
	public List<M> find(String sql, Object... paras) {
		Config config = _getConfig();
		Connection conn = null;
		try {
			conn = config.getConnection();
			return find(conn, sql, paras);
		} catch (Exception e) {
			throw new ActiveRecordException(e);
		} finally {
			config.close(conn);
		}
	}
```
此时并没有在config中的threadLocal变量设置connection,threadLocal中的conn为null,不存在线程销毁时threadLocal中的conn未释放情况
2.在执行事务操作时(如Db.tx()或Tx拦截器),虽然将connection设置到threadLocal变量中,但是在finally语句中关闭了connection,也将connection从threadLocal中移除
``` java
boolean tx(Config config, int transactionLevel, IAtom atom) {
		Connection conn = config.getThreadLocalConnection();
		...
		try {
                        ...
		} finally {
			try {
				if (conn != null) {
					if (autoCommit != null)
						conn.setAutoCommit(autoCommit);
					conn.close();
				}
			} catch (Throwable t) {
				LogKit.error(t.getMessage(), t);	// can not throw exception here, otherwise the more important exception in previous catch block can not be thrown
			} finally {
				config.removeThreadLocalConnection();	// prevent memory leak
			}
		}
	}
```

综上,不会出现线程销毁后连接未释放的情形

**Comment by 0x0001** [comment]
> @0x0001 我看了jfinal 3.4的源码
> 1.使用Model.findFirst()等方法时会调用Model.find()
> 
> ```java
> 	public List<M> find(String sql, Object... paras) {
> 		Config config = _getConfig();
> 		Connection conn = null;
> 		try {
> 			conn = config.getConnection();
> 			return find(conn, sql, paras);
> 		} catch (Exception e) {
> 			throw new ActiveRecordException(e);
> 		} finally {
> 			config.close(conn);
> 		}
> 	}
> ```
> 
> 此时并没有在config中的threadLocal变量设置connection,threadLocal中的conn为null,不存在线程销毁时threadLocal中的conn未释放情况
> 2.在执行事务操作时(如Db.tx()或Tx拦截器),虽然将connection设置到threadLocal变量中,但是在finally语句中关闭了connection,也将connection从threadLocal中移除
> 
> ```java
> boolean tx(Config config, int transactionLevel, IAtom atom) {
> 		Connection conn = config.getThreadLocalConnection();
> 		...
> 		try {
>                         ...
> 		} finally {
> 			try {
> 				if (conn != null) {
> 					if (autoCommit != null)
> 						conn.setAutoCommit(autoCommit);
> 					conn.close();
> 				}
> 			} catch (Throwable t) {
> 				LogKit.error(t.getMessage(), t);	// can not throw exception here, otherwise the more important exception in previous catch block can not be thrown
> 			} finally {
> 				config.removeThreadLocalConnection();	// prevent memory leak
> 			}
> 		}
> 	}
> ```
> 
> 综上,不会出现线程销毁后连接未释放的情形

干的漂亮, 不过这个issue应该是在1.x版本的时候提的
