### ISSUE TITLE
Validator的开关变量shortCircuit难以全局设置

### ISSUE THREAD

**Issue by ssbunny** [jfinal/jfinal#88]
如果想默认设置 shortCircuit 为 true, 除了提供一个继承自 Validator 的统一基类，目前没发现有什么好的方式。而如果仅为了一个属性值的改变，提供一个基类且改变所有的继承结构，显得很笨拙。

**Comment by jfinal** [comment]
在具体的 XxxValidator 类中调用一次 setShortCircute(true); 也是很方便的

**Comment by ssbunny** [comment]
@jfinal 不算方便。1. 如果不写统一基类，XxxValidator 类的数量太多。2. 如果想统一改回 false ，又得重新来一遍。一般一个应用的验证提示方式是统一的，应该提供统一的开关吧？在统一开关的基础上再提供现在已经实现的 setShortCircute 会比较好。另外就是，我觉得 jFinal 的 Validator 有些粗糙，引入的类也过多，否则又得降级到分支语句，增加圈复杂度。

**Comment by jfinal** [comment]
@ssbunny 可以很容易扩展的，大至方法如下：
`
public class ShortCircuteValidator extends Validator {
  public  ShortCircuteValidator() {
    setShortCircute(true);
  }
}
`
然后需要用的地方直接继承这个类。另外 jfinal 的 validator具体有哪些粗糙之处可以提出些建议，作者也方便不断改进这里。最后引入的类只有一个，不知过多是指什么？
