### ISSUE TITLE
 关于Control.getModel()方法中 TypeConverter.convert()方法的问题。

### ISSUE THREAD

**Issue by wen3062** [jfinal/jfinal#9]
关于这个地方，我post传过来的参数需要的就是空字符串，不是null

public static final Object convert(Class<?> clazz, String s) throws ParseException {
        // mysql type: varchar, char, enum, set, text, tinytext, mediumtext, longtext
        if (clazz == String.class) {
            return ("".equals(s) ? null : s);   // 用户在表单域中没有输入内容时将提交过来 "", 因为没有输入,所以要转成 null.
5
        }
这里你给默认转成null了。这里默认是什么样就是什么样比较好吧，主要是字符串类型。

并且我还不想一个一个的set进去，那样就不方便了。

------------
可以提供一个参数设置，是否需要转成null，并且这个开放出来，可以自己实现，因为会有这样的需求，默认的不满足。

**Comment by jfinal** [comment]
j
