### ISSUE TITLE
Render问题

### ISSUE THREAD

**Issue by RoonyLi** [jfinal/jfinal#91]
``` java```
    public Render getDefaultRender(String view) {
        ViewType viewType = constants.getViewType();
        if (viewType == ViewType.FREE_MARKER) {
            return new FreeMarkerRender(view + constants.getFreeMarkerViewExtension());
        } else if (viewType == ViewType.JSP) {
            return new JspRender(view + constants.getJspViewExtension());
        } else if (viewType == ViewType.VELOCITY) {
            return new VelocityRender(view + constants.getVelocityViewExtension());
        } else {
            return mainRenderFactory.getRender(view + mainRenderFactory.getViewExtension());
        }
    }
```

上面这段代码处理了各种render的viewExtension问题，但这只是在defaultrender的时候才会起作用，在单独调用某一个render，比如renderJsp的时候，里面的代码就变成了：

``` java```
    /**
     * Render with jsp view
     */
    public void renderJsp(String view) {
        render = renderFactory.getJspRender(view);
    }

     public Render getJspRender(String view) {
        return new JspRender(view);
    }
```

这样的话就不会有viewExtension的处理，设置的viewExtension就不起作用了。建议将这个viewExtension的处理放到render类的构造函数里处理，这样，就都可以生效了。

**Comment by jfinal** [comment]
@RoonyLi 这个 viewExtension 一开始就是专为 default render设计的，也就是说，当用户在本次请求过程中没有调用过任何render方法，那么jfinal会默认给调用一个，规则是 view = controllerKey + methodName + viewExtension，所以此时就需要一个 viewExtension 才能正确获取到具体的模板。而非 default render在调用时，用户明确指定了 viewExtension，自然这个值就不需要了。当然这样设计的确不太优雅

**Comment by jfinal** [comment]
@RoonyLi 这里我再补充解析一下，为何用户在明确调用 render时需要指定 viewExtension。首先从代码量上来说，提供这个viewExtension通常只增加了五个字符左右，例如： render("abc.html")，但是增加的这五个字符会提升代码的可读性，一眼就知道 "abc.html" 是个模板文件，读起来比 render("abc") 语义更加明确。其次，在 render方法调用时提供viewExtension，可以避免字符串拼接，从而提升一点性能。当然目前是带来了一个让人误解的 viewExtension 的用法的问题，这个以后我会想办法消除，例如，或许可以去掉 default render 这个概念，没有 render的话，jfinal默认也不处理，那么 viewExtension 这个配置也就可以直接删掉了

**Comment by RoonyLi** [comment]
@jfinal 我明白你考虑的问题，但还有一个我的考虑是这样的，一般在开发的时候会指定mainRenderFactory，默认的render其实已经知道在渲染的到底是什么了，语义依然简单清晰。目前流行的spring mvc，Struts都支持该种设计，相信开发人员理解应该不成问题。关于性能其实影响不大，毕竟也支持设置过默认的模板文件夹，也有字符串的拼接。另外，除了render，在特别调用某种render，比如renderJsp的时候，对于extension其实一般是jsp，每次都增加一个.jsp的后缀其实意义不大。
