### ISSUE TITLE
StrKit验证js post数据问题

### ISSUE THREAD

**Issue by 0312birdzhang** [jfinal/jfinal#93]
从js post上来的数据为空，Controller获取到的为<code>null</code>，StrKit.isBlank(str)缺少判断字符串为<code>null</code>的情况

提交了pr https://github.com/jfinal/jfinal/pull/94

**Comment by jfinal** [comment]
"null" 值是一个字符串常量，而 null 值是另一个常量，并非字符串，这两者在逻辑上是不同的，不能这样子处理，感谢反馈

**Comment by 0312birdzhang** [comment]
我在debug的时候发现传入的是 "null"字符串，通过了<code>validateRequiredString</code>校验，所以也感觉很奇怪。

**Comment by 0312birdzhang** [comment]
应该是我理解错了Validator的<code>validateRequiredString</code>，需要先设置<code>setShortCircuit(true);</code>，这样在校验失败的时候直接不继续执行了。
