### ISSUE TITLE
Cookie的归属问题

### ISSUE THREAD

**Issue by linkerlin** [jfinal/jfinal#98]
调试网站发现一个问题：
如果网站部署在localhost:8080
cookie必须设置在localhost，不能带端口号。
不知道这个算不算是 jfinal的BUG?

**Comment by tom-zhb** [comment]
cookie和域名有关，和端口无关

**Comment by jfinal** [comment]
jfinal 的 cookie 操作仅仅是转调了底层的 HttpServletRespones 的相关方法，所以出现 bug 的可能性几乎是没有的，cookie 是不分端口号的 :)
