### ISSUE TITLE
无主键表生成_MappingKit.java的问题

### ISSUE THREAD

**Issue by flhuoshan** [jfinal/jfinal#99]
使用自动生成时_MappingKit.java时，
对于无主键表，会生成类似这样：arp.addMapping("BZB_MAIN", "", BzbMain.class);
导致启动项目报Primary key can not be blank，
而实际上应该生成这样：
arp.addMapping("BZB_MAIN",  BzbMain.class);
就可以解决

**Comment by jfinal** [comment]
无主键不能使用 Active record 模式， 这种情况需要使用 Db + Record 模式
